{% set name = "jupyter-resource-usage" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 622c5d57ea713401d8c0143189cf31ad6aadebd49a2a044927a422600f9f7e91

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - jupyter_server >=2.0.0,<3
    - psutil >=5.6.0,<6
    - python >={{ python_min }}
    - pyzmq >=19

test:
  imports:
    - jupyter_resource_usage
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter-resource-usage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Server Extension for monitoring Resource Usage
  description: |
    Jupyter Server Extension for monitoring Resource Usage
  dev_url: https://github.com/jupyter-server/jupyter-resource-usage

extra:
  recipe-maintainers:
    - krassowski
    - jtpio
