{% set name = "jupyter-resource-usage" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d10d53525027206fb5f190964d4535bdb269fd241773fc09c87af02a974a5c7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging >=0.7.9,<0.8.0
  run:
    - jupyter_server >=1.0.0,<2
    - psutil
    - python >=3.6

test:
  imports:
    - jupyter_resource_usage
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter-resource-usage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Server Extension for monitoring Resource Usage
  description: |
    Jupyter Server Extension for monitoring Resource Usage
  dev_url: https://github.com/jupyter-server/jupyter-resource-usage

extra:
  recipe-maintainers:
    - jtpio
